### ISSUE TITLE
Roadmap/TODO

### ISSUE THREAD

**Issue by n-luke-th** [ngzh-luke/self-myMY-m1#1]
# myMY Mark 1 Roadmap

### Short-term (Versions 0.0.0 - 0.9.0)
* [ ] #2
* [ ] **Splash Screen & Authentication Implementation** (0.1.0)
* [ ] **Setting Page & Navbar Implementation** (0.2.0)
* [ ] #3
* [ ] **UI Page Drafting and Structuring** (0.3.0)
* [ ] **Able to add new party, payment info identifier, and transaction** (0.4.0)
* [ ] **Theming System Implementation** (0.5.0)
* [ ] **Able to add new transaction** (0.6.0) 
* [ ] **Fetch and List Data from <https://countriesnow.space> API** (0.7.0)
* [ ] **Transaction Record Listing (All & Last 5)** (0.8.0)
* [ ] **Transaction Template & Proof (1:1) with Small File Size** (0.9.0)

### Long-term (Future Versions)
* [ ] **Add Analytics Charts** (X.X.X)
* [ ] **Transaction Promise, Payment Information, & Account Balancing** (X.X.X)
* [ ] **Bill-Splitting System (KBank Khunthong Inspired)** (X.X.X)
* [ ] **Ability to Search (and/or) Query the (Own) Records** (X.X.X)
* [ ] **Ability to Export Records either both PDF and (CSV,JSON) format or one of them** (X.X.X)
* [ ] **Add support for alternative noSQL (Document) database** (X.X.X)
* [ ] **Add statements: Privacy Policy (Thailand's PDPA focused, with potentially GDPR compliance), Terms of Services, Refund Policy, etc.** (X.X.X)
* [ ] **Implement the Feedback system** (X.X.X)
* [ ] **Host with your own choice** (X.X.X)
* [ ] **Integrated with AI functionalities** (X.X.X)
* [ ] **Budgeting functionalities** (X.X.X)
* [ ] **Home widgets support on native mobile apps** (X.X.X)
* [ ] **Able to share the transaction records via QR code or link** (X.X.X)
* [ ] **Referer system & promo code** (X.X.X)
* [ ] **In-app update center: news, announcements, etc.** (X.X.X)
* [ ] **trip mode (travel mode )** (X.X.X)

## Features Under Consideration

* [ ] **In-App Advertisement System** (Withdrawn)

**Note:** 
labels to GitHub issues to indicate their status 
- `planned`
- `in-progress`
- `consideration`
- `withdrawn`
- `needs-triage`
